apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: heavenhold-ai:latest
          imagePullPolicy: Never
          env:
            - name: DEV_BROKER_URL
              value: "redis://redis-service:6379/0"
          command: ["celery", "-A", "app.app:celery", "beat", "--loglevel=info"]
